/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pm.presentation.example.lib;

import java.nio.file.Files;
import java.nio.file.Path;
import javax.swing.JTree;

/**
 *
 * @author user
 */
public class FilesTree extends JTree {
    private Path selectedPath;
    /**
     * Creates new form FilesTree
     */
    public FilesTree() {
        initComponents();
    }
    public FilesTree(FilesTreeNode rootNode) {
        super(rootNode);
        initComponents();
    }
    public void setSelectedPath(Path sp) {
        selectedPath = sp;
    }

    public Path getSelectedPath() {
        return selectedPath;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filesPopupMenu1 = new pm.presentation.example.lib.FilesPopupMenu();

        addTreeWillExpandListener(new javax.swing.event.TreeWillExpandListener() {
            public void treeWillCollapse(javax.swing.event.TreeExpansionEvent evt)throws javax.swing.tree.ExpandVetoException {
            }
            public void treeWillExpand(javax.swing.event.TreeExpansionEvent evt)throws javax.swing.tree.ExpandVetoException {
                formTreeWillExpand(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formTreeWillExpand(javax.swing.event.TreeExpansionEvent evt)throws javax.swing.tree.ExpandVetoException {//GEN-FIRST:event_formTreeWillExpand
        FilesTreeNode node = (FilesTreeNode) evt.getPath().getLastPathComponent();
        if (node.getUserObject() == null || Files.isDirectory((Path) node.getUserObject())) {
            node.loadChildren();
        }
    }//GEN-LAST:event_formTreeWillExpand


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pm.presentation.example.lib.FilesPopupMenu filesPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
