/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pm.presentation.example.lib;

import javax.swing.JMenuItem;

/**
 *
 * @author user
 */
public class ShowPropertiesMI extends JMenuItem {

    /**
     * Creates new form ShowPropertiesMI
     */
    public ShowPropertiesMI() {
        initComponents();
    }
    public ShowPropertiesMI(FilesMainPanel filesMP) {
        super(new ShowPropertiesAction(filesMP));
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setText("File/Dir Properties");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
